CREATE TABLE dbo.NEWS (
	MESSAGE_ID BIGINT NOT NULL,
	CHAT_ID BIGINT NOT NULL,
	MESSAGE_DATE DATETIMEOFFSET NOT NULL,
	MESSAGE_DATA NVARCHAR(MAX),
	CONSTRAINT PK_NEWS PRIMARY KEY CLUSTERED (MESSAGE_ID, CHAT_ID)
);